### ISSUE TITLE
Client docs: No h2/h3 are displaying in the right hand nav or the docs page itself

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#10]
For some reason, the h2/h3 tags are not displaying within the docs article or on the right hand nav.

See https://5c7dc06c86dd760008a87e71--apollo-client-docs.netlify.com/docs/react/essentials/local-state for an example. The docs page should have all the same headings as: https://www.apollographql.com/docs/react/essentials/local-state.html

**Comment by trevorblades** [comment]
Fixed by 07ef63b9e192d1ce3e9dc7b0590c95ac47b1fe9f
