### ISSUE TITLE
Add ability to pass additional Remark plugins

### ISSUE THREAD

**Issue by b-gibbs** [apollographql/gatsby-theme-apollo#104]
I'd like to add additional Remark plugins to gatsby-plugin-mdx, as discussed here

https://www.gatsbyjs.org/docs/theme-api/#configuration

and here

https://github.com/gatsbyjs/gatsby/issues/16697

This doesn't appear to be possible, atm. Is this something you'd consider adding?

Thanks,

Brad

**Comment by iwaffles** [comment]
Hey @b-gibbs were you able to sort this out? If so, would you mind sharing what you did?

**Comment by afuh** [comment]
any news on this?

**Comment by trevorblades** [comment]
This is fixed by https://github.com/apollographql/gatsby-theme-apollo/commit/690ded22445bbaf12f4415b0d3fa00b1b470b37b and will be available in a new release shortly! Thanks for raising this issue @b-gibbs 🎉

**Comment by b-gibbs** [comment]
Thanks!
