### ISSUE TITLE
Algolia Config

### ISSUE THREAD

**Issue by jsbrain** [apollographql/gatsby-theme-apollo#108]
Hi Trevor!

Nice work, love the theme! 
I was wondering:
The Algolia integration isn't really intended for external use or at least not for use out of the box?

When I try to use it it doesn't work so I guess the index has to be crawled by myself with the docker crawler provided by DocSearch and then after the index already exists the config with ApiKey and IndexName should work or is there even more to it?

Thanks in advance

**Comment by heitorlessa** [comment]
/md
I've recently got it working with no problems

1. Signed up with DocSearch for an open source repo
2. They've created a crawler for the project and [sent me the config I could change via PR](https://github.com/algolia/docsearch-configs/blob/master/configs/aws-lambda-powertools-python.json)
3. [Updated the theme config](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/gatsby-config.js) to use the `index` and `key` they sent me

Hope that helps

**Comment by jsbrain** [comment]
That helps! Thank you so much! :)

**Comment by trevorblades** [comment]
Thanks for the answer @heitorlessa! I've added a section in the theme's readme that should help to explain this concept: https://github.com/apollographql/gatsby-theme-apollo/tree/master/packages/gatsby-theme-apollo-docs#algolia-configuration
