### ISSUE TITLE
Client docs: TSDoc API generator not working

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#11]
For the Apollo Client docs, we use TSDoc to automatically generate API docs. Currently, they're not showing up in the Client docs: https://5c7dc06c86dd760008a87e71--apollo-client-docs.netlify.com/docs/react/api/apollo-client

**Comment by peggyrayzis** [comment]
- [ ] Change the color of the teal inline code to body copy
- [ ] Change the styling of the heading so it is consistent with the uppercase styling on the left hand nav
- [ ] Match the grey fill behind the banner to what we have in the code block
- [ ] Round the corners to match the border radius of the code block
- [ ] Make the line height consistent with what we use elsewhere
- [ ] Sitewide: remove default underline on links, show underline on hover unless it's inline code (which should be default underlined in pink)
- [ ] Fix backticks in headings (React Apollo API docs)

**Comment by trevorblades** [comment]
Partially fixed by c2bde9ebd3b14d4d45855d7471411d1152cae839 and 5aea35c08d5e8f701715d39ca51df7c47baa98b5
