### ISSUE TITLE
Bug? You're viewing documentation for a previous version of this software

### ISSUE THREAD

**Issue by heitorlessa** [apollographql/gatsby-theme-apollo#118]
Hey @trevorblades,

 I'm hitting an odd issue that I can't quite reproduce in my own laptop, and I suspect it might be a deployment issue (GitHub pages). 

 This wasn't happening before I enabled DocSearch but I can't seem to draw a connection, and find it must be something else.

 **Supporting files/info**

* [Gatsby config](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/gatsby-config.js)
* [page-layout.js LOC where this notification appears](https://github.com/apollographql/gatsby-theme-apollo/blob/c387496e08c8095769c4d9a2e23a94e3209cfb88/packages/gatsby-theme-apollo-docs/src/components/page-layout.js#L253)
* Recent changes
    - Enabled Search
    - Removed gatsby-offline-plugin

 **Reproducing**

It doesn't work for me but somehow happens in other people's browser (chrome, firefox)

* Visit: https://awslabs.github.io/aws-lambda-powertools-python/
* Search for “metrics”, click in any result and see if you hit either of these
    - “You’re viewing documentation for a previous version of this software” might appear at the top
    - **Side effect**: search focus might remain despite you clicking on a result 

Any pointers is more than appreciated - Screenshot below 

![image](https://user-images.githubusercontent.com/3340292/83145212-5eb70480-a0ec-11ea-8d8f-dbd176824248.png)

**Comment by heitorlessa** [comment]
Managed to reproduce it! This only happens when you hit a search result that goes to a sub-directory (not Gatsby) that hosts other HTML files. 

If you search for `metrics`, and select any result that has `Module` in its subtitle it'll hit this issue.

**Comment by heitorlessa** [comment]
I've updated docSearch to no longer show results for non-Gatsby website, and that works.

**Comment by trevorblades** [comment]
Oh this is an interesting bug either way. Thanks for reporting this. Is your current solution sufficient, or would you ideally still like to surface non-Gatsby results in your search?

**Comment by heitorlessa** [comment]
Hey Trevor,

 It’d be great to surface non-Gatsby results as I initially had the crawler
to show both doc content + API reference (generated by another tool)

 For now, I’ve updated Docsearch to not index /api content:

https://github.com/algolia/docsearch-configs/commit/9406b6373ef680587799f92ba9b4e0150ba27fc1

—-

That also made me curious about how to have docs for different branches
(develop, master) — Is there somewhere I can learn how to do that?

I think I saw WP GraphQL or another project example doing that with your
theme.

Thanks again for the support

**Comment by heitorlessa** [comment]
Reopening as I've just noticed this also happens when you use `footerNavConfig`

```javascript
                footerNavConfig: {
                    'API Reference': {
                        href: 'https://awslabs.github.io/aws-lambda-powertools-python/api/'
                    },
...
```

If I were to click on the link it causes this issue

![image](https://user-images.githubusercontent.com/3340292/83348114-9955b280-a321-11ea-98f0-08da3ec1774c.png)


If I refresh the page after hitting the issue, it works

![image](https://user-images.githubusercontent.com/3340292/83348139-ae324600-a321-11ea-8fba-0d5d504a6131.png)

**Comment by heitorlessa** [comment]
> Reopening as I've just noticed this also happens when you use `footerNavConfig`
> 
> ```js
>                 footerNavConfig: {
>                     'API Reference': {
>                         href: 'https://awslabs.github.io/aws-lambda-powertools-python/api/'
>                     },
> ...
> ```
> 
> If I were to click on the link it causes this issue
> 
> ![image](https://user-images.githubusercontent.com/3340292/83348114-9955b280-a321-11ea-98f0-08da3ec1774c.png)
> 
> If I refresh the page after hitting the issue, it works
> 
> ![image](https://user-images.githubusercontent.com/3340292/83348139-ae324600-a321-11ea-8fba-0d5d504a6131.png)

I shadowed the `docset-switcher` after some digging, and I add an explicit `target` attribute if known -- Full commit here

https://github.com/awslabs/aws-lambda-powertools-python/commit/29a670451c5bd3eea00d245962463278280cac00
