### ISSUE TITLE
Collapsed Sidebar Icon

### ISSUE THREAD

**Issue by isimonsm** [apollographql/gatsby-theme-apollo#119]
Hello,

we encountered an issue with changing the sidebar logo.

We changed the icon similar to the documentation by adding a logo.js file:
```jsx
import React from "react";
import logo from "./images/favicon-colored.svg";

export default function Logo() {
  return (
    <img
      src={logo}
      width="100"
      alt="logo"
    />
  );
}
```

It works for the uncollapsed sidebar, but when you resize the window the sidebar collapses and the logo on the sidebar icon is still the apollo icon.

Uncollapsed:
![image](https://user-images.githubusercontent.com/51827407/83891411-68281880-a74d-11ea-8880-3b75ed0bc989.png)

Collapsed:
![image](https://user-images.githubusercontent.com/51827407/83891456-79712500-a74d-11ea-901f-d14543ceeb71.png)

Is there a possibility to change the collapsed logo, too?

**Comment by trevorblades** [comment]
Yes you can! Try shadowing the `mobile-logo.js` file. You might even be able to get away with something like this:

// src/gatsby-theme-apollo-docs/components/logo.js
```js
import React from "react";
import logo from "./images/favicon-colored.svg";

export default function Logo() {
  return (
    <img
      src={logo}
      width="100"
      alt="logo"
    />
  );
}
```

// src/gatsby-theme-apollo-docs/components/mobile-logo.js
```js
export default from './logo'
```

**Comment by isimonsm** [comment]
Thank you very much, I could just shadow mobile-logo.js as you said :)
```javascript
// src/gatsby-theme-apollo-docs/components/mobile-logo.js
export { ReactComponent as MobileLogo } from "./images/favicon-colored.svg";
```
