### ISSUE TITLE
"Expand all" option for left nav?

### ISSUE THREAD

**Issue by glasser** [apollographql/gatsby-theme-apollo#12]
I like the cleanliness of having the left nav be closed to sub-headers, but I'm wondering if there's a nice looking way to get an expand/collapse all button in there. When trying to find some obscure sub-document it's helpful to be able to see the full table of contents easily.

**Comment by trevorblades** [comment]
Good call @glasser! I'll get @itsjessmarina's thoughts on this and we can hopefully come up with a good solution for this.

**Comment by trevorblades** [comment]
Fixed by bfb9836d8cb6fdbe54b4e44370a7463d025de5d2
