### ISSUE TITLE
Gatsby Starter for this theme

### ISSUE THREAD

**Issue by tungandy** [apollographql/gatsby-theme-apollo#126]
Dear Sir/Madam,

Which starter should I use before installing this theme?  I tried the Gatsby-Starter and then added this theme but seems to throw the below error.  What am i doing wrong?

```
There was an error in your GraphQL query:
Cannot query field "childMdx" on type "File".
```

Thanks,
Andy

**Comment by trevorblades** [comment]
Hey Andy, this theme supports a mixture of Markdown and MDX content, and as a result, requires at least one MD and one MDX file to be present in your content directory. To get around this issue, you should create at least one of each type of file. One of them could even be empty and not linked to within your site.

I understand this is unintuitive, but this is a limitation of the way that Gatsby creates (or doesn't create) GraphQL nodes when it doesn't find any content to source for a particular type (MDX in this case).
