### ISSUE TITLE
Theme: track scroll state in the nav

### ISSUE THREAD

**Issue by daniman** [apollographql/gatsby-theme-apollo#14]
Scrolling around the new docs site, I feel I’m really missing the scroll state being tracked in the nav. I would like for there to be some sort of indicator in the nav showing me which section I’m reading, otherwise I get lost in all the content and my own understanding of where I am on the page.

**Comment by trevorblades** [comment]
Fixed by 80ccb5ac6f3e7e1c00f469648b6310fa95c9bf65
