### ISSUE TITLE
contentDir ignored for component shadowing

### ISSUE THREAD

**Issue by KonkretneKosteczki** [apollographql/gatsby-theme-apollo#140]
Within options of the gatsby-theme-apollo-docs one can set the contentDir option, however that option will still be ignored for the purpose of component shadowing.

Let's say i want to customize logo, I would create a logo.js file under the `/${contentDir}/gatsby-theme-apollo-docs/components/` directory, however, as long as the contentDir is not `src` the file will be ignored.

The project documentation is a part of has it's own source code under src directory which is why i cannot use it.

**Comment by trevorblades** [comment]
Oh I see! So when working with Gatsby component shadowing, your directory structure must _always_ be `src/THEME_NAME/subdirectory`, regardless of what you set your `contentDir` option as.

The `contentDir` in this theme refers to the directory where all of your Markdown and MDX content lives, and where it can expect to look when sourcing that.

To be clear, if you want to shadow components, you'll always need to put them within `src/gatsby-theme-apollo-docs` no matter what you pass as a `contentDir` option.
