### ISSUE TITLE
Theme: Remember expansion states

### ISSUE THREAD

**Issue by evans** [apollographql/gatsby-theme-apollo#16]
When navigating, the left nav closes whenever navigating on the page. This leads to an annoying experience, where I have trouble remembering what I was trying to look at/which overall section it's stored in. 

![screen recording 2019-03-06 at 03 17 pm](https://user-images.githubusercontent.com/5565407/53920980-c5518d80-4023-11e9-9fe8-af0764698561.gif)

My impression is that this can be solved with localStorage or maybe even link-state 🤔

**Comment by trevorblades** [comment]
Fixed by 15efd6767ef64a9d43c0170eeed6c8c7a9878842
