### ISSUE TITLE
Headers in docs are overlapping elements above it

### ISSUE THREAD

**Issue by rafalolszewski94** [apollographql/gatsby-theme-apollo#161]
**Problem:**
Headers are overlapping elements that are above them, in this case - buttons.

**Solution:**
Remove minus margin (`-25`) on H2 element

See attached screenshot and line of code causing it below.

![Screenshot from 2020-11-13 15-34-31](https://user-images.githubusercontent.com/37925892/99083595-0acea800-25c6-11eb-8266-82a0c17800e7.png)

https://github.com/apollographql/gatsby-theme-apollo/blob/84ab228ba28192ee9de2187954c9a169c80e4887/packages/gatsby-theme-apollo-docs/src/components/page-content.js#L65

**Comment by jgarrow** [comment]
Thanks for the heads up! We've pushed out a [patch here](https://github.com/apollographql/apollo/pull/1070) that addresses the issue.
