### ISSUE TITLE
Theme: Line numbers don't line up with code properly

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#18]
In the code block, the alignment between the line numbers and the code looks a bit off. Ideally, the line numbers and code should be aligned on the bottom of the line instead of the top:

<img width="834" alt="1__Build_a_schema_-_Apollo_Docs" src="https://user-images.githubusercontent.com/18017067/54233619-aa7b8f00-44e3-11e9-8997-e5a13b234305.png">

**Comment by trevorblades** [comment]
Fixed by 37bead267a952b26fc969f6d7c362c14b389d9d9 
![lines](https://user-images.githubusercontent.com/1216917/54789479-cf60b800-4bef-11e9-94e8-ccfab8dad456.png)
