### ISSUE TITLE
Compatibility with Gatsby V3

### ISSUE THREAD

**Issue by jaymdq** [apollographql/gatsby-theme-apollo#181]
I tried to install this plugin in a Gatsby V3 project with no luck.

```
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.13.80" from gatsby-theme-apollo@3.0.3
```

This may help? 
https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers

**Comment by trevorblades** [comment]
Good catch @jaymdq. Just changed the peer dependency from `^2.13` to `>=2.13`, so you shouldn't see that error anymore. Hope this helps!
