### ISSUE TITLE
Theme: Add previous/next cards to bottom of page

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#19]

**Comment by peggyrayzis** [comment]
@trevorblades can we please line up the prev/next cards with the page content instead of the right hand nav? On wide screens, it's trailing off too far to the right.

**Comment by trevorblades** [comment]
Fixed by dc4b3277ed35d22e372276699b73275b057acca4 and ec0a9ccd860687ff077ce78d16de6613e91b212c
