### ISSUE TITLE
Update links to community

### ISSUE THREAD

**Issue by EduardoGHdez** [apollographql/gatsby-theme-apollo#202]
I just set a PR for updating some of the links to the community in the
apollo repo, but noticed the documentation links are managed in another
package.

I wonder if there is any initiative for updating those. If not, just let me know and I'd be more than happy to help :smile:

PR: [doc: Update community links](https://github.com/apollographql/federation/pull/769)

**Comment by trevorblades** [comment]
Just merged the PR on the federation repo. We'll make some time to update the "Discuss on spectrum" links in the docs sidebar some time in the future.

Thanks for your help, and PRs are always welcome 😄

**Comment by EduardoGHdez** [comment]
Would it be okay if I just go ahead and update it?
I mean, took a quick look at the project structure, and seems something easy to do, but wanted to confirm it was okay to do so or that there was no initiative or someone else already working on it

**Comment by trevorblades** [comment]
Yeah that would be great! It's currently in our backlog, but you won't be stepping on anybody's toes if you opened a PR for that change.
