### ISSUE TITLE
Theme: In this section animation

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#21]
When I scroll the page, I want the right hand nav (Is this section) to stay fixed where it is while the header and line divider scroll off the page. Something about scrolling the right hand nav up all the way up to the top navbar feels a bit distracting and takes my eye off the content.

Maybe it just needs more margin between the top navbar and the right hand nav?

**Comment by trevorblades** [comment]
Fixed by ec0a9ccd860687ff077ce78d16de6613e91b212c
