### ISSUE TITLE
Flickering seen when scrolling in Safari

### ISSUE THREAD

**Issue by justinanastos** [apollographql/gatsby-theme-apollo#23]
Video: https://cl.ly/e28eab7f4c37

I could not capture this with a screen capture.

---

I navigated to https://www.apollographql.com/docs/platform/schema-validation#setup and see the page flickering when scrolling. To be more specific, it appears as though this image is appearing and disappearing after I release the mouse and the browser continues it's inertial scrolling.

![](https://cl.ly/72bd337c1202/Image%202019-03-26%20at%2010.38.47%20AM.png)

Mac OS 10.14.3 (I did _not_ install the March 25th, 2019 update). Safari 12.0.3.

**Comment by trevorblades** [comment]
Thanks for the detailed issue! I'm unable to recreate the bug on my machine (I have the same OS and Safari versions as you), but I'm going to try on my roommates computer.

**Comment by trevorblades** [comment]
This is partially addressed by 827acf466e271924c86f6490bfa81d0a34b10720. @debergalis reported that the jittery scroll had been fixed, but still notices some image flickering. @justinanastos could you test it again on your machine and let me know if any of the issues you noticed are still there?

**Comment by justinanastos** [comment]
@trevor-scheer The jittery scroll has been fixed and I still notice some image flickering. Does the docs page lazily load images? Is it possible it's trying to reload the image whenever it scrolls into view, temporarily removing the image content and then restoring it?

**Comment by justinanastos** [comment]
@trevorblades The jittery scroll has been fixed and I still notice some image flickering. Does the docs page lazily load images? Is it possible it's trying to reload the image whenever it scrolls into view, temporarily removing the image content and then restoring it?

**Comment by justinanastos** [comment]
@trevorblades Something else to keep an eye on; components shouldn't misbehave because they are impure. That seems like a yellow flag that something strange is going on with the rendering or React lifecycle methods. In other words, if a component behaves strangely when rendered repeatedly, there's something wrong with the component.

**Comment by trevorblades** [comment]
@justinanastos ok, thanks for the update! The image isn't lazy loading, but I'll reexamine the way I'm rendering things so see if I can get to the bottom of this.

**Comment by trevorblades** [comment]
This should be resolved as of de0ca3f62ce6ff8a1f736d38f49b19bfff40aff1. I moved the scroll-watching logic to a component with much lower rerender cost than the outer component that I was previously using
