### ISSUE TITLE
Theme: Code blocks should have a footer with a copy button

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#3]
Before launch, our code block should have a footer with:
- A copy button that copies the text within the code block to the user's keyboard
- A filename that should be set similar to how we do line highlighting, like this:

```
```lines=4,7 file="src/index.js"
```

Design reference: https://apollographql.atlassian.net/jira/software/projects/DX/boards/7?selectedIssue=DX-9

**Comment by trevorblades** [comment]
Fixed by 88a1afd9c53df2b6d5b8d3f43af7950cbfc435bb
