### ISSUE TITLE
Theme: maintain left nav scroll position when clicking between different articles

### ISSUE THREAD

**Issue by daniman** [apollographql/gatsby-theme-apollo#30]
Clicking different articles in the left nav bar resets the scroll position of the nav every time you click to a new article. This leads to a "jumpy" feeling if you're just trying to browse through different articles and you end up needing to re-scroll to the position you were at before.

It would be really nice if we could maintain this scroll position. The https://gatsbyjs.org/docs/ site does it, so it seems like it should be feasible in Gatsby themes :)

**Comment by trevorblades** [comment]
Fixed by #58
