### ISSUE TITLE
Using this theme requires Node >= 10

### ISSUE THREAD

**Issue by hwillson** [apollographql/gatsby-theme-apollo#31]
Since this theme uses the [experimental fs promises API](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_promises_api), it will only run on Node >= 10. We might want to mention this in the `README` of each of our docs repos, so people understand why they're running into errors like the following, when attempting to start docs locally using say Node 8:

![Screenshot 2019-04-16 16 08 34](https://user-images.githubusercontent.com/137740/56240900-896a0900-6062-11e9-9b79-000115e65b5b.png)

**Comment by trevorblades** [comment]
The theme no longer uses the `fs` module
