### ISSUE TITLE
Anchors in the URL shouldn't be case sensitive

### ISSUE THREAD

**Issue by justinanastos** [apollographql/gatsby-theme-apollo#35]
I would expect the hash at the end of URL intended to scroll to a heading of a page to be case insensitive. It appears to be case sensitive.

Works: https://www.apollographql.com/docs/apollo-server/features/data-sources#http-methods

Does not work: https://www.apollographql.com/docs/apollo-server/features/data-sources#HTTP-Methods

**Comment by trevorblades** [comment]
This was fixed by a5ff4b4bc8aa16e5dcded8857f5e59b01a329912 and will be included in the next release (1.0.16)
