### ISSUE TITLE
What page am I on?

### ISSUE THREAD

**Issue by justinanastos** [apollographql/gatsby-theme-apollo#37]
Given that I'm on a long docs page and I scroll past the top, I can see the sections of the current page and they highlight as I scroll. This is awesome. However, I don't know what section I'm currently in. Maybe we could replace the `In this section` text with the current section name?

![image](https://user-images.githubusercontent.com/5224118/56602960-a5265f80-65cc-11e9-885c-0487b2f041e9.png)

**Comment by trevorblades** [comment]
Good call, @justinanastos! This idea is implemented in 5b78d516f528401478a6a1d79f203963f0b01962 and will be included in the next release
