### ISSUE TITLE
Formatting glitch

### ISSUE THREAD

**Issue by gschmidt** [apollographql/gatsby-theme-apollo#49]
In this page, formatting codes are not being interpreted:
https://www.apollographql.com/docs/react/essentials/mutations/

Actual result: Raw markdown codes visible
<img width="732" alt="Screen Shot 2019-07-13 at 1 15 08 PM" src="https://user-images.githubusercontent.com/143488/61176135-47246b00-a570-11e9-9c3d-e8c32e35d98b.png">

Expected(?) result: Formatting similar to the corresponding section of the Queries page
<img width="739" alt="Screen Shot 2019-07-13 at 1 15 52 PM" src="https://user-images.githubusercontent.com/143488/61176148-67ecc080-a570-11e9-99f8-61264911ab44.png">

Chrome: Version 75.0.3770.100 (Official Build) (64-bit)
OSX: 10.14.5 (18F132)

**Comment by trevorblades** [comment]
Fixed by https://github.com/apollographql/apollo-client/pull/5222
