### ISSUE TITLE
Theme: Inline code-highlighting font appears to be too small

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#5]
The font size for inline code highlighting looks too small compared with the rest of the body text.

In this screenshot, you can see that the font size for the inline code highlighted text is the same, regardless of whether the body text is smaller or larger. Ideally, the font size for inline code highlighting should scale with the body text:

<img width="1107" alt="mocking_-_apollo_docs" src="https://user-images.githubusercontent.com/18017067/53824238-82b78480-3f41-11e9-9ad0-6197dff78240.png">

Lmk if this is confusing, I'm not sure if I'm explaining this well 🤦‍♀️

**Comment by peggyrayzis** [comment]
https://deploy-preview-2394--apollo-server-docs.netlify.com/docs/apollo-server/features/mocking is a good page to test this on :)

**Comment by trevorblades** [comment]
Fixed by https://github.com/apollographql/gatsby-theme-apollo/commit/ebb03547aeb6eda02fad0c64a246a439ead322b1#diff-8b70b4d3ea7d79cbded16cd7f6eb01adR51
