### ISSUE TITLE
More Abstract Theme Implementation

### ISSUE THREAD

**Issue by GoPro16** [apollographql/gatsby-theme-apollo#54]
Hi!

Our team is referencing your theme pretty closely for developing our own documentation site. I see this as a means of maybe collaborating on a more abstract package/theme that could store more abstractable components such as the top navigation, side nav, and/or main content window.

Our theme is still in the works and subject to change but figured I would mention and get the ball rolling rather than wait until after the fact. We use our own ukit which is based off of `bootstrap 4` and `reactstrap`.

https://github.com/Availity/gatsby-theme-availity

**Comment by trevorblades** [comment]
That's awesome to hear! Right now, I'm working on exactly that: a more abstract implementation of the theme where everything that currently uses hard-coded Apollo-specific values will be configurable either by passing theme options, or shadowing theme components/files.

This work is taking place in [the `v2` branch](https://github.com/apollographql/gatsby-theme-apollo/tree/v2), and I'm hoping to have it released in the next week or two!

**Comment by GoPro16** [comment]
Nice! I figured you guys would want to do that eventually.

Since we are using bootstrap I have found it hard to overwrite any of the default theme that was provided for the navigation, content, and section nav. 

I think at its core, it would be nice just to have a theme that has all the configurations for mdx, and prism. That way at minimum people can use the theme without having to pull in the whole `styled-components` library.

We have a different use case since we have multiple mono repos with different packages, each of our pages would need its own version selector. If the base version dropdown was an addition to the current them that would make the base more easy to implement. As I was implementing our own version a good chunk of the `gatsby-node` config was striped out due to omitting this.

From what I am seeing in your `v2` implementation it looks like you are sill tying people down to the apollo theme for the docs. Its almost as if there would be some small package that is just the underlying configurations for `gatsby-node` that is configurable. We haven't finalized our whole layout yet but we did like the general feel of your docs so we took some of what you guys implemented.

I would say that 1 item we missed that I am working on implementing now is `react-live`. I believe with your current implementation it would have to be tweaked a fair amount in order for it to work. That is removing the `MDXRenderer`  from the layout. I was taking note of how [doctocat](https://github.com/primer/doctocat) implemented their docs with the shadowing rendering combined with [wrapPageElement](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement) to get both the live editor and prism preview.

Maybe a plugin would help out in this more than an abstracted theme. This is one of my first times actually diving deep into the gatsby space so I probably don't know enough to give any solid recommendations but just a synopsis of what I have had to do to replicate you all's layout to fit our needs.

**Comment by wrod7** [comment]
@trevorblades im going to piggyback off this thread. am i able to customize or remove the docset switcher?

![image](https://user-images.githubusercontent.com/7082435/66434847-6dcc3380-e9f1-11e9-85d6-880b174e534d.png)

also where can i change the favicon?

**Comment by trevorblades** [comment]
All good questions @wrod7! Currently you can't do those things but I'll add some configuration options to allow that this week :+1:

**Comment by trevorblades** [comment]
@wrod7 I've updated the theme to make it easier to replace the favicon and provided a description of how to do this here: https://github.com/apollographql/gatsby-theme-apollo/tree/master/packages/gatsby-theme-apollo-docs#component-shadowing

**Comment by wrod7** [comment]
@trevorblades this is great. thank you!

**Comment by trevorblades** [comment]
Update: I just merged #96 which aims to take account of all the theme options and reduce the number of options required to make the theme work. I managed to strip it down pretty far and added a "required" column to the options table in the readme to make this factor more clear.

Also, you can avoid rendering the docset switcher by omitting the `navConfig` theme option entirely. 

Closing this PR now!
