### ISSUE TITLE
Update Peer Dependencies | React, React DOM

### ISSUE THREAD

**Issue by GoPro16** [apollographql/gatsby-theme-apollo#57]
I'm probably missing something here but it doesn't look like `react` or `react-dom` is included as a `dependency` here and its magically working.

I was noticing this on my project and figured I would open an issue here as well.

**Comment by trevorblades** [comment]
Thanks for noticing this! I've added `react` and `react-dom` to the themes' peer dependencies in bb5a854feb4597c233af293e3bcab9daa0a1c0a9
