### ISSUE TITLE
Theme: "In this section" on the right hand nav should be bold

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#6]
In the design, "In this section" should be bold. Currently, it's not appearing as bold.

<img width="225" alt="developer_experience_-_agile_board_-_jira" src="https://user-images.githubusercontent.com/18017067/53824433-ed68c000-3f41-11e9-8f75-3ba50f8bfb92.png">

**Comment by trevorblades** [comment]
Fixed by 7b1704c13883bd744395f805ed36a9627880e938
