### ISSUE TITLE
How to change the colors?

### ISSUE THREAD

**Issue by SvenAlHamad** [apollographql/gatsby-theme-apollo#61]
Hi,

I'm trying to use this theme for one of my own projects. 

I'm in the process of branding the theme to fit more towards our own visual appearance. I've installed the v2 of `gatsby-theme-apollo-docs` and managed to change the logo via component shadowing, but now I'm a bit stuck with colors. What is the intended way of tweaking the colors? Is there a way to assign something like a primary color, so it's applied throughout the theme?

Cheers

**Comment by trevorblades** [comment]
Hey @SvenAlHamad! You sure can change the color palette in this theme. You'll want to shadow [`gatsby-theme-apollo-core/utils/colors`](https://github.com/apollographql/gatsby-theme-apollo/blob/master/packages/gatsby-theme-apollo-core/src/utils/colors.js).

You can check out all of the available keys in the linked file. If you want to keep _most_ of the colors intact but only change a few of them, you can shadow the file like so:

```js
// src/gatsby-theme-apollo-core/utils/colors.js
const {colors} = require('gatsby-theme-apollo-core/src/utils/colors');

exports.colors = {
  ...colors,
  primary: '#ff0000' // change the primary color to red
};
```

Here's what the result of this change looks like:

![Screen Shot 2019-09-24 at 1 19 48 PM](https://user-images.githubusercontent.com/1216917/65547291-1052c580-dece-11e9-872a-d84726a561d3.png)

**Comment by wrod7** [comment]
@trevorblades thanks for this. whats the next step after adding that colors.js file? do I need to edit something in the gatsby-config?

**Comment by trevorblades** [comment]
@wrod7 you shouldn't need to edit anything in your Gatsby config once you set up your custom colors.js file. Just restart your build and you should see the new colors 👍

Let me know if you're seeing something different!

**Comment by trevorblades** [comment]
@wrod7 you've almost got it! If you want to shadow the logo, you'll want to do that in your `src/gatsby-theme-apollo-core` directory rather than the `gatsby-theme-apollo` one. I realized that the core theme docs were still telling users to shadow the logo in the way that you are, so I updated that section: https://github.com/apollographql/gatsby-theme-apollo/tree/master/packages/gatsby-theme-apollo-core#logotitle

Your directory structure should look like this when you're done:

```
|-- source
    |-- index.mdx
|-- src
    |-- assets
         |-- custom-logo.svg
    |-- gatsby-theme-apollo-core
        |-- components
            |-- logo.js
        |-- utils
            |-- colors.js
|-- gatsby-config.js
```

And your `logo.js` file could look like this:

```js
export {ReactComponent as default} from '../assets/custom-logo.svg';
```

**Comment by wrod7** [comment]
that was it it! gonna play with it some more. Thanks again for this package!
