### ISSUE TITLE
Docsearch Config Needs to Be Updated

### ISSUE THREAD

**Issue by GoPro16** [apollographql/gatsby-theme-apollo#63]
The selector for the main heading needs to be updated to account for the style changes.

https://github.com/algolia/docsearch-configs/blob/master/configs/apollodata.json#L24

Right now all of the docs are showing as `Documentation` as the main heading. If this was intended you can close. I wanted to open the issue here so that you guys at least get the notification.

If it is an issue I can create a PR on their github repo to fix it but not sure if they will accept as I am not a contributor/member of this org.

**Comment by trevorblades** [comment]
Thank you for identifying this issue @GoPro16! I'm going to create a fix for it this week. I'll update this issue when the fix is ready.

**Comment by trevorblades** [comment]
This is addressed by 3f96fcf036210377b0e744e477250bea817da530. We should see the results going back to normal once Algolia has re-indexed everything. Thanks for the heads up @GoPro16!
