### ISSUE TITLE
Client docs: Version switcher on Client docs not working between 2.5 and 2.4

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#7]
Currently on the Apollo Client docs, we have version switching available between versions 2.5 and 2.4. I'm not seeing any version switching available for the client docs PR:

https://5c7dc06c86dd760008a87e71--apollo-client-docs.netlify.com/docs/react/

**Comment by trevorblades** [comment]
Fixed by 31e319ca6bd110f61ea8a3ba6faf4b2cb6336b34
