### ISSUE TITLE
TypeScript Generics break MultiCodeBlock syntax highlighting

### ISSUE THREAD

**Issue by stemmlerjs** [apollographql/gatsby-theme-apollo#77]
**Summary**: I'm using `MultiCodeBlock` to present TypeScript code blocks but when I use TypeScript Generics, the styling breaks from that line until the end of the code block.

Here's an example:

Given this block:

```client.mdx
_src/index.tsx_

<MultiCodeBlock>

```tsx
import { ApolloClient } from 'apollo-client';
import { InMemoryCache, NormalizedCacheObject } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';

const cache: ApolloClient<NormalizedCacheObject> = new InMemoryCache();
const link = new HttpLink({
  uri: 'http://localhost:4000/'
});

const client = new ApolloClient({
  cache,
  link
});
```

</MultiCodeBlock>

We might see:

![Screen Shot 2019-12-10 at 1 36 55 PM](https://user-images.githubusercontent.com/6892666/70558093-35acb280-1b52-11ea-8af5-48a66134c39d.png)

I suspect it has something to do with being interpreted as JSX or an HTML element.

Watch what happens when I add a closing tag to `NormalizedCacheObject`.

![Screen Shot 2019-12-10 at 1 37 16 PM](https://user-images.githubusercontent.com/6892666/70558104-3b09fd00-1b52-11ea-866e-80e75b3e0b66.png)

Though the code is syntactically incorrect, the rest of the styles in the code block can be applied.

Any ideas on this one?

**Comment by trevorblades** [comment]
In your example, your codeblock is tagged as `tsx`. I think you're right, the generic is being treated like an opening JSX tag. If you change that tag to `ts`, you'll see the correct highlighting like this:
![Screen Shot 2019-12-12 at 4 14 10 PM](https://user-images.githubusercontent.com/1216917/70759277-bb6b6200-1cfa-11ea-9907-2125fce4059b.png)

[This comment](https://github.com/PrismJS/prism/issues/1401#issuecomment-383379427) addresses this issue pretty well. The code highlighter that we use has to make a decision about how to color each bit of code, and it doesn't necessarily _know_ whether you're trying to open a JSX tag or using TS generics.

**Note:** You can keep the `src/index.tsx` filename even if the codeblock is using `ts` syntax highlighting!
