### ISSUE TITLE
TypeScript blocks with unused imports get removed when switching to JS

### ISSUE THREAD

**Issue by stemmlerjs** [apollographql/gatsby-theme-apollo#79]
This is an interesting one. 

**Summary**: Unused (yet essential) imports in TypeScript code blocks are removed in the resulting JavaScript code because they're assumed to be TypeScript types/constructs (types, interfaces, etc).

Check out this GIF for example. The first two lines get nuked.

![sjdlkjflksdj](https://user-images.githubusercontent.com/6892666/70642462-3c4c3000-1c0d-11ea-8ce7-79e3a6ed59a5.gif)

**Comment by trevorblades** [comment]
Fixed by https://github.com/trevorblades/gatsby-remark-typescript/commit/0c5b033d1847461e0217a5c4461957bf09860615
