### ISSUE TITLE
Server docs: Broken image on Server docs

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#8]
https://deploy-preview-2394--apollo-server-docs.netlify.com/docs/apollo-server/features/errors#default-information is displaying a broken image in the default information section with the alt text "Screenshot demonstrating an error stacktrace and additional"

**Comment by trevorblades** [comment]
Fixed by 4dd527c19e5248a4a9057deba5e76759d8686096
