### ISSUE TITLE
Wrong repository link inside the apollo client documentation

### ISSUE THREAD

**Issue by apalazzin** [apollographql/gatsby-theme-apollo#83]
Hi,
following the documentation under https://apollographql.com/client, I've found a link unavailable (https://github.com/apollographql/apollo-client/blob/master/src/src/ApolloClient.ts#L75 will produce a 404 error).

I've attached an image to show where is located the problem.

![Core - Client  React  - Apollo GraphQL Docs](https://user-images.githubusercontent.com/11698463/72064641-97d90e80-32dc-11ea-9e3e-5e34f918e9b8.png)

The problem is the word "src" repeated 2 times in the url.

**Comment by trevorblades** [comment]
Good catch @apalazzin! I've made [a change](https://github.com/apollographql/gatsby-theme-apollo/commit/3b02774f47737cd93306ac45564c928dcd04276f) that will fix this in the next client docs deploy 👍

**Comment by trevorblades** [comment]
Fixed as of today thanks to https://github.com/apollographql/apollo-client/pull/5822!

**Comment by apalazzin** [comment]
@trevorblades thanks for the update.
