### ISSUE TITLE
BUG | color shadowing doesn't work 

### ISSUE THREAD

**Issue by louisgv** [apollographql/gatsby-theme-apollo#85]
# Description

I followed https://github.com/apollographql/gatsby-theme-apollo/issues/61#issuecomment-534731053 to test out overshadowing color but it seems something has changed internally over at space-kit that causes a palette check with the new color?

# Screenshot:

![image](https://user-images.githubusercontent.com/6723574/72272677-e38dff80-35dd-11ea-97be-f0628b196adb.png)

![image](https://user-images.githubusercontent.com/6723574/72272698-eee12b00-35dd-11ea-8d58-e601076ed341.png)

**Comment by louisgv** [comment]
A work-around I discovered is to use the colors from `space-kit`:

```
const { colors } = require("gatsby-theme-apollo-core/src/utils/colors")
const {colors : spaceKitColors} = require('@apollo/space-kit/colors');

exports.colors = {
  ...colors,
  primary: spaceKitColors.red.base,
}
```

The above works.

**Comment by trevorblades** [comment]
Thanks for catching this @louisgv! It does seem that using Space Kit colors is the only way to avoid this error.

Some background: A while back, this theme started using components like `Button` from the Space Kit component library. One of the unexpected side effects of this is that this component (and others) expect custom colors to be one of the ones defined [in the Space Kit docs](https://space-kit.netlify.com/?path=/story/color--brand-colors).

I'm going to update the readme and the codesandbox example to reflect this change 👍

**Comment by trevorblades** [comment]
I've updated the theme readmes to accurately show how to shadow colors, and updated [the shadowing example on CodeSandbox](https://codesandbox.io/s/mq7p0z3wmj) accordingly!

**Comment by KonkretneKosteczki** [comment]
Using the custom colors does not work because some of the elements depending on the state ex. hovered will adjust the color (make it lighter or darker) by using the palette the color came from. Since custom colors are not present in any palette it causes the issue.
As such I found a slightly dirty workaround that involves extending existing color palettes os spaceKitColors.

You could create a custom color palette if you were to:
```
// src/gatsby-theme-apollo-core/utils/color.js
const {colors} = require('gatsby-theme-apollo-core/src/utils/colors');
const {colors: spaceKitColors} = require('@apollo/space-kit/colors');

// noinspection JSValidateTypes
spaceKitColors.custom = {
  darkest: "#172a3a",
  darker: "#172a3a",
  dark: "#172a3a",
  base: "#172a3a",
  light: "#172a3a",
  lighter: "#172a3a",
  lightest: "#172a3a",
}

exports.colors = {
  ...colors,
  primary: spaceKitColors.custom.dark,
  primaryLight: spaceKitColors.custom.lighter,
}
```

It's dirty because it invalidates the typings for color palettes, and might make it harder for them to be directly used within components.
