### ISSUE TITLE
Logo layout bug in Safari

### ISSUE THREAD

**Issue by braco** [apollographql/gatsby-theme-apollo#86]
Exists on live Apollo Docs site as well as theme.

Safari Version 13.0.4 (15608.4.9.1.3)

<img width="524" alt="Screen Shot 2020-01-19 at 1 54 19 PM" src="https://user-images.githubusercontent.com/2449172/72686495-7b4e8a80-3ac3-11ea-920f-b8d80e5750d5.png">

**Comment by trevorblades** [comment]
Thanks for pointing this out @braco! This has been fixed by 1b562831a51187c1c3e4f46a76aea3fbb7f34073 and will appear in the next release of this theme.
