### ISSUE TITLE
contentDir is ignored

### ISSUE THREAD

**Issue by braco** [apollographql/gatsby-theme-apollo#87]
It seems that the contentDir config is being ignored?

Even when set to:

```
        contentDir: 'docs/src',
```

Gatsby will fail based on "source" not existing.

**Comment by pabloest** [comment]
I see the same behavior on my build.

**Comment by trevorblades** [comment]
@braco @pabloest thanks for pointing this out! I've created a proposed set of changes in #94 that should address this issue. These changes would be breaking and imply a major verison bump but I'm curious to hear your thoughts on this approach if you have any feedback!

**Comment by pabloest** [comment]
@trevorblades I like the approach you outlined there and I think that should address confusion around the source of the site vs the source of Markdown files.

**Comment by trevorblades** [comment]
Closed by #94
