### ISSUE TITLE
Request: arbitrary labels in MultiCodeBlock

### ISSUE THREAD

**Issue by braco** [apollographql/gatsby-theme-apollo#89]
https://github.com/apollographql/gatsby-theme-apollo/blob/748705f1327c72d145db697ecdf6337d712b1ee4/packages/gatsby-theme-apollo-docs/src/components/multi-code-block.js#L115

It doesn't seem like there's a way to include another language like Python currently.

> \```python
> \```

Results in an empty dropdown item:

<img width="134" alt="Screen Shot 2020-01-20 at 10 33 39 PM" src="https://user-images.githubusercontent.com/2449172/72773394-f81d5980-3bd4-11ea-9a00-0532c48d67f1.png">

**Comment by trevorblades** [comment]
Good catch @braco! I've fixed this in d617c19c27f727f5d90f5be960d7cd60b05090f3 by using the provided language (`lang`) and capitalizing the first letter if we don't have a custom label set up for the language.

```js
label:
  // try to find a label or capitalize the provided lang
  langLabels[lang] || lang.charAt(0).toUpperCase() + lang.slice(1)
```
