### ISSUE TITLE
Theme: Hovering over h2/h3/h4 and clicking should link to anchor tag

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/gatsby-theme-apollo#9]
Hovering over an h2/h3 and clicking should link you to its anchor tag (https://www.apollographql.com/docs/apollo-server/features/errors.html - we even have a link icon appear next to the text). Currently, the only way for me to access the anchor tag is to click the heading in the right hand nav. A user should also be able to click on the heading itself to link to its anchor tag.

See https://deploy-preview-2394--apollo-server-docs.netlify.com/docs/apollo-server/features/errors for an example.

**Comment by trevorblades** [comment]
Fixed by 2ffb87f94129019334d4b3589fb09635d02e0392
