### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by CodeAndWeb** [apollographql/gatsby-theme-apollo#91]
I'd like to use your docs theme (or at least parts of it) for a documentation project. The problem that I have is that you've not set a license here nor on npm.

Using it under MIT license would be great.

**Comment by trevorblades** [comment]
Thanks for pointing this out @CodeAndWeb! I've fixed this in 7e3fd2646d73b81060a1701a66ee3e84119eea30 and 310ed723d59fe7a37033b80ed1e1d37997cf3df4
